title: CONCERT
email: xinglu@shao.ac.cn
personal_website: https://xinglunju.github.io
description: >-
  Coordinated Observations of Nebulae in the Central Molecular Zone Exploring gas Recycling and Transformation
url: "https://CMZconcert.github.io"

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
