title: CONCERT
email: xinglu@shao.ac.cn
description: >-
  Coordinated Observations of Nebulae in the Central Molecular Zone Exploring gas Recycling and Transformation
url: "https://CMZconcert.github.io"
github_username: CMZconcert

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
